package com.uno.scoreboards.domain.scoreboard.events;

public enum EventsEnum {
  CREATED_SCOREBOARD,
  SCOREBOARD_LOCKED,
  ADDED_PLAYER,
  ADDED_ROUND_TO_HISTORY,
  REVERTED_HISTORY_TO_ROUND,
  REACHED_PLAYER_TARGET_SCORE,
  UPDATED_PLAYER_POINTS
}
